# question 1

In [2]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# question 2

In [3]:
import numpy as np
a1=[] 
a2=[]
for i in range(0, 5): #first array
    no1 = int(input())
    a1.append(no1)
for i in range(0, 5): #second array
    no2 = int(input())
    a2.append(no2) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

1
2
3
4
5
6
7
9
8
10
[ 1  2  3  4  5  6  7  9  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


# question 3

In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)
print(arr.size)

2
9


# question 4

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=arr
arr=arr[:, np.newaxis]
print(arr)
arr=np.expand_dims(arr1,2)
print(arr)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


C:\Users\vsudh\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  


# question 5

In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack(arr))
print(np.hstack(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# question 6

In [14]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3], dtype=int64))
